### ISSUE TITLE
Add mlr3proba to task view

### ISSUE THREAD

**Issue by RaphaelS1** [aallignol/survival_task_view#3]
Hi, I would appreciate if mlr3proba (https://CRAN.R-project.org/package=mlr3proba) could be added to the Survival task view. It is a machine learning package, part of the mlr3 ecosystem, which implements survival models including classical models (Cox, AFT) and machine learning models(random forests, SVMs). Thanks!

**Comment by aallignol** [comment]
Done (with a lot of delays; I apologise).
