### ISSUE TITLE
Duplicated sections

### ISSUE THREAD

**Issue by eribul** [aallignol/survival_task_view#5]
It seems those sections are duplicated:
- Multivariate Survival
- Bayesian Models
- High-Dimensional Data

The first two of those semms identical but the third differn between its apperences.

**Comment by eribul** [comment]
I delete this issue since the repository seems inactive.

**Comment by aallignol** [comment]
I'm very slow but not inactive. I'll start the update process this week. 

Thanks for opening the issue.

**Comment by eribul** [comment]
Sorry :-)
I just went through all my open issues everywhere and tried to currate that list to make it more managageble!
Thanks for the response!

**Comment by aallignol** [comment]
That's now fixed. Thanks
