### ISSUE TITLE
Proposal: frailtypack for the entire family of frailty models

### ISSUE THREAD

**Issue by Generalized** [aallignol/survival_task_view#6]
@aallignol I would suggest adding the frailtypack package. It's a huge package supporting shared and frailty models, allowing one to model both competing risks and recurrent events at the same time.

Citation: _Rondeau V, Gonzalez JR. frailtypack: a computer program for the analysis of correlated failure time data using penalized likelihood estimation. Comput Methods Programs Biomed. 2005 Nov;80(2):154-64. doi: 10.1016/j.cmpb.2005.06.010. Epub 2005 Sep 6. PMID: 16144730._

![obraz](https://user-images.githubusercontent.com/60151643/104883094-7b969580-5964-11eb-90e0-73720c1d814c.png)
https://www.jstatsoft.org/article/view/v047i04

CRAN: https://cran.r-project.org/web/packages/frailtypack/index.html

ResearchGate: https://www.researchgate.net/publication/239808125_frailtypack_An_R_Package_for_the_Analysis_of_Correlated_Survival_Data_with_Frailty_Models_Using_Penalized_Likelihood_Estimation_or_Parametrical_Estimation

**Comment by aallignol** [comment]
The frailtypack package is already included. Is there some specific wording you'd like to include?

**Comment by Generalized** [comment]
Oh, I'm sorry. I must have missed it. Please don't mind it. I'm closing it. Thank you!
